return {
  "rcarriga/nvim-dap-ui",
  -- opts = {
  --   layouts = {
  --     {
  --       elements = {
  --         {
  --           id = "scopes",
  --           size = 0.7,
  --         },
  --         {
  --           id = "breakpoints",
  --           size = 0.2,
  --         },
  --         {
  --           id = "stacks",
  --           size = 0.1,
  --         },
  --       },
  --       position = "left",
  --       size = 40,
  --     },
  --     {
  --       elements = {
  --         {
  --           id = "repl",
  --           size = 1,
  --         },
  --       },
  --       position = "bottom",
  --       size = 15,
  --     },
  --   },
  --   mappings = {
  --     edit = "e",
  --     expand = { "<CR>", "<2-LeftMouse>" },
  --     open = "o",
  --     remove = "d",
  --     repl = "r",
  --     toggle = "t",
  --   },
  -- },
}
